keys:
  - sample-filesystem-$(openssl sha1 < package.json)-$(openssl sha1 < yarn.lock)
  - sample-filesystem-$(openssl sha1 < package.json)
  - sample-filesystem-$(git branch --format '%(refname)')

storage:
  - filesystem: /var/tmp/bags-sample-filesystem-storage
